### ISSUE TITLE
In timer trigger azure function, main function is being called twice

### ISSUE THREAD

**Issue by Khushboo-Mulani** [BrianRosamilia/azure-function-log-intercept#10]
in index.js for timer azure function,

module.exports = async function (context, myTimer) {
    intercept(context);
    if (myTimer.IsPastDue) {
        console.log('myTimeris running late!');
    }
    console.log("myTimer scheduler just ran!")
};

Getting every log twice while using "intercept(context)", this is totally strange!

**Comment by BrianRosamilia** [comment]
hey, this was a breaking change and is being tracked in #11 

I didn't completely understand what you were saying and I didn't realize the issue was only locally.  Sorry!
