### ISSUE TITLE
Amazon Lex context .... Thanks!

### ISSUE THREAD

**Issue by donniekerr** [BrianRosamilia/azure-function-log-intercept#2]
Just wanted to say thanks for sharing this!  I was debugging posting to Lex Bot all day and discovered Lex api has its own "context" that conflicts with azure function context!  So, I never saw any errors!  You saved me!

**Comment by BrianRosamilia** [comment]
I'm so glad to hear it!  My pleasure!  When I released this package I thought people wouldn't even understand its purpose haha.

Btw feel free to star this repo if you like!  Somehow I have loads of npm downloads but few stars (No pressure at all though, just think people might feel weird about installing a library with just 5 stars!)
